### ISSUE TITLE
Erreur dans tous le code

### ISSUE THREAD

**Issue by akhlaaqbadulla** [TristanBoulesteix/Pendu#2]
Salut,
j'esseiller de utiliser quelque parti de ton code mais jarrive pas a tourner le program. j'utilise eclipse comme IDE. Pourais tu m'aider s'il t plait.
merci en avance

**Comment by TristanBoulesteix** [comment]
Bonjour,
Désolé pour ma réponse vraiment très en retard mais GitHub ne m'avait pas notifié qu'il y avait un problème ouvert.
Pour faire tourner le programme, il faut mettre deux dossiers "penduUserAccount" et "Settings" à la racine du projet sous Eclipse.

Dans tous les cas, je déconseille l'usage de ce code. Il s'agit d'un vieux programme qui ne respecte pas ou peu les bonne pratique de programmation et de l'orienté objet.
